version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.1

master_only: &master_only
  filters:
    branches:
      only: master

jobs:
  deploy:
    docker:
      - image: cimg/node:18.20.3
    environment:
      AWS_DEFAULT_REGION: "eu-central-1"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          role_arn: $AWS_ROLE_ARN
          role_session_name: "lighthouse-deploy-from-circleci"
      - run:
          name: Deploy
          command: |
            npm ci
            npm run deploy

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - deploy:
          <<: *master_only